---
- hosts: all
  roles:
    - dokku_bot.ansible_dokku
    - geerlingguy.swap
  vars:
    # If you are running dokku on a small VPS, you'll most likely
    # need some swap to ensure you don't run out of RAM during deploys
    swap_file_size_mb: '2048'
    dokku_version: 0.32.3
    dokku_users:
      - name: root
        username: root
        ssh_key: "{{lookup('file', '~/.ssh/id_rsa.pub')}}"
    dokku_plugins:
      - name: clone
        url: https://github.com/crisward/dokku-clone.git
      - name: postgres
        url: https://github.com/dokku/dokku-postgres.git
      - name: letsencrypt
        url: https://github.com/dokku/dokku-letsencrypt.git
  tasks:
    - name: create app
      dokku_app:
        # change this name in your template!
        app: &appname readquran
    - name: environment configuration
      dokku_config:
        app: *appname
        config:
          # specify port so `domains` can setup the port mapping properly
          PORT: "8080"

    - name: postgres:create default
      dokku_service_create:
        name: default
        service: postgres

    - name: postgres:link default readquran
      dokku_service_link:
        app: *appname
        name: default
        service: postgres

    - name: ports:set http:80:80
      dokku_ports:
        app: *appname
        mappings:
          - http:80:8080

    - name: ports:set http:80:80
      dokku_ports:
        app: *appname
        mappings:
          - https:443:8080
    # - name: add domain
    #   dokku_domains:
    #     app: *appname
    #     domains:
    #       - example.com
    # - name: add letsencrypt
    #   dokku_letsencrypt:
    #     app: *appname
